package it.dogior.hadEnough.settings

internal const val COLOR_BACKGROUND = "#11141A"
internal const val COLOR_CARD = "#1A2029"
internal const val COLOR_CARD_ALT = "#202733"
internal const val COLOR_CARD_DISABLED = "#151922"
internal const val COLOR_TEXT = "#F4F7FB"
internal const val COLOR_MUTED = "#96A2B5"
internal const val COLOR_STROKE = "#2E3746"
internal const val COLOR_ACCENT = "#4CC9F0"
internal const val COLOR_SUCCESS = "#7CFF9D"
internal const val COLOR_DANGER = "#FF7F7F"
internal const val COLOR_THUMB_OFF = "#8A94A6"
internal const val COLOR_TRACK_OFF = "#39424F"
internal const val COLOR_INPUT_FILL = "#10151D"
internal const val COLOR_PERFORMANCE = "#A3E635"
internal const val COLOR_DISPLAY = "#14B8A6"
internal const val COLOR_HOME = "#60A5FA"
internal const val COLOR_SOURCES = "#FBBF24"
internal const val COLOR_SUPPORT = "#FB7185"
internal const val COLOR_SCORE = "#FDE047"
internal const val COLOR_ANIME_VARIANTS = "#C084FC"
internal const val COLOR_EPISODES = "#FB923C"
internal const val COLOR_SOURCE_UPDATE = "#2DD4BF"
internal const val COLOR_SOURCE_ANIME = "#8B5CF6"
internal const val COLOR_SOURCE_TV = "#0EA5E9"
internal const val COLOR_FEEDBACK = "#818CF8"
internal const val COLOR_TELEGRAM = "#229ED9"
internal const val COLOR_VISUAL_EFFECTS = "#E879F9"
internal const val COLOR_VISUAL_BLUR = "#D8B4FE"
internal const val COLOR_VISUAL_HEADER = "#FDE68A"
internal const val COLOR_PARTICLES = "#38BDF8"
internal const val COLOR_API_CHECK = "#06B6D4"
internal const val COLOR_STREMIO = "#D946EF"
internal const val COLOR_CLOUDSTREAM_SERVICES = "#7DD3FC"
internal const val COLOR_RESET = "#F97316"
internal const val COLOR_BACKUP = "#2DD4BF"
internal const val COLOR_HOME_ANIME = "#F472B6"
internal const val COLOR_HOME_TV = "#34D399"
internal const val COLOR_HOME_MOVIE = "#F59E0B"
internal const val COLOR_HOME_TRACKING = "#A78BFA"
internal const val COLOR_HOME_CHANNELS = "#22D3EE"
internal const val COLOR_CATALOGS = "#38BDF8"
internal const val STREAMING_COMMUNITY_UPDATED_LINK_PAGE =
    "https://telegra.ph/Link-Aggiornato-StreamingCommunity-09-29"
internal const val TELEGRAM_ICON_URL = "https://telegram.org/img/t_logo.png"

internal fun tint(color: String, alphaHex: String): String =
    "#$alphaHex${color.removePrefix("#")}"
